version: '2'
services:
    evhunt-app:
        image: evhunt
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://evhunt-mysql:3306/evhunt?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    evhunt-mysql:
        extends:
            file: mysql.yml
            service: evhunt-mysql
